### ISSUE TITLE
Which folder do you unzip to 

### ISSUE THREAD

**Issue by pt321** [gautierlabarre/unified-remote-gnome-mpv#1]
is this a  plugin?

**Comment by gautierlabarre** [comment]
Hi, 
You can unzip wherever you want. I would advise a specific folder. Then on your unified remote server you can specify the above location. 

Everything is explained here : 
https://github.com/gautierlabarre/unified-remote-celluloid#installation

Note that you have to have a full version of unified remote to add specific remotes like this one.

**Comment by pt321** [comment]
ok sorry, I mistook this as a plugin for celluloid that can get LIRC working with it
